"""initial_schema

Revision ID: 7823a499a745
Revises: 
Create Date: 2026-04-01 02:27:28.112094
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '7823a499a745'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_users_username'), 'admin_users', ['username'], unique=True)
    op.create_table('app_config_entries',
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('is_secret', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('filings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=24), nullable=False),
    sa.Column('accession_number', sa.String(length=64), nullable=True),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('form_type', sa.String(length=50), nullable=False),
    sa.Column('tier', sa.Integer(), nullable=False),
    sa.Column('sec_items', sa.JSON(), nullable=False),
    sa.Column('raw_feed_summary', sa.Text(), nullable=True),
    sa.Column('entry_link', sa.String(length=1000), nullable=False),
    sa.Column('primary_document_url', sa.String(length=1000), nullable=True),
    sa.Column('raw_document_text', sa.Text(), nullable=True),
    sa.Column('document_char_count', sa.Integer(), nullable=False),
    sa.Column('analysis_status', sa.String(length=32), nullable=False),
    sa.Column('analysis_error', sa.Text(), nullable=True),
    sa.Column('telegram_status', sa.String(length=255), nullable=False),
    sa.Column('telegram_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_filings_accession_number'), 'filings', ['accession_number'], unique=False)
    op.create_index(op.f('ix_filings_entry_link'), 'filings', ['entry_link'], unique=True)
    op.create_index(op.f('ix_filings_form_type'), 'filings', ['form_type'], unique=False)
    op.create_index(op.f('ix_filings_published_at'), 'filings', ['published_at'], unique=False)
    op.create_index(op.f('ix_filings_ticker'), 'filings', ['ticker'], unique=False)
    op.create_index(op.f('ix_filings_tier'), 'filings', ['tier'], unique=False)
    op.create_table('ingestion_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('entries_seen', sa.Integer(), nullable=False),
    sa.Column('matched_entries', sa.Integer(), nullable=False),
    sa.Column('new_filings', sa.Integer(), nullable=False),
    sa.Column('updated_filings', sa.Integer(), nullable=False),
    sa.Column('analyzed_filings', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('llm_usage_alert_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('period_key', sa.String(length=16), nullable=False),
    sa.Column('metric_name', sa.String(length=64), nullable=False),
    sa.Column('metric_unit', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('threshold_percent', sa.Float(), nullable=False),
    sa.Column('limit_value', sa.Float(), nullable=False),
    sa.Column('observed_value', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('telegram_delivery_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('raw_payload', sa.JSON(), nullable=False),
    sa.Column('triggered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'period_key', 'metric_name', 'threshold_percent', name='uq_llm_usage_alert_events_provider_period_metric_threshold')
    )
    op.create_index(op.f('ix_llm_usage_alert_events_period_key'), 'llm_usage_alert_events', ['period_key'], unique=False)
    op.create_index(op.f('ix_llm_usage_alert_events_provider'), 'llm_usage_alert_events', ['provider'], unique=False)
    op.create_table('llm_usage_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=True),
    sa.Column('feature', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('requests', sa.Integer(), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('reasoning_tokens', sa.Integer(), nullable=False),
    sa.Column('cached_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=True),
    sa.Column('extra_metrics', sa.JSON(), nullable=False),
    sa.Column('raw_payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llm_usage_events_created_at'), 'llm_usage_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_llm_usage_events_provider'), 'llm_usage_events', ['provider'], unique=False)
    op.create_table('llm_usage_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('period_key', sa.String(length=16), nullable=False),
    sa.Column('period_started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('primary_metric', sa.String(length=64), nullable=False),
    sa.Column('primary_unit', sa.String(length=32), nullable=False),
    sa.Column('primary_value', sa.Float(), nullable=False),
    sa.Column('totals', sa.JSON(), nullable=False),
    sa.Column('raw_payload', sa.JSON(), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'source', 'period_key', name='uq_llm_usage_snapshots_provider_source_period')
    )
    op.create_index(op.f('ix_llm_usage_snapshots_period_key'), 'llm_usage_snapshots', ['period_key'], unique=False)
    op.create_index(op.f('ix_llm_usage_snapshots_provider'), 'llm_usage_snapshots', ['provider'], unique=False)
    op.create_index(op.f('ix_llm_usage_snapshots_synced_at'), 'llm_usage_snapshots', ['synced_at'], unique=False)
    op.create_table('price_ingestion_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('requested_tickers', sa.Integer(), nullable=False),
    sa.Column('successful_tickers', sa.Integer(), nullable=False),
    sa.Column('failed_tickers', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('price_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('currency', sa.String(length=16), nullable=True),
    sa.Column('exchange', sa.String(length=64), nullable=True),
    sa.Column('market_state', sa.String(length=32), nullable=True),
    sa.Column('regular_market_price', sa.Float(), nullable=True),
    sa.Column('previous_close', sa.Float(), nullable=True),
    sa.Column('change_amount', sa.Float(), nullable=True),
    sa.Column('change_percent', sa.Float(), nullable=True),
    sa.Column('day_low', sa.Float(), nullable=True),
    sa.Column('day_high', sa.Float(), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('market_cap', sa.Float(), nullable=True),
    sa.Column('source_payload', sa.JSON(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_snapshots_fetched_at'), 'price_snapshots', ['fetched_at'], unique=False)
    op.create_index(op.f('ix_price_snapshots_ticker'), 'price_snapshots', ['ticker'], unique=False)
    op.create_table('telegram_chats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_chat_id', sa.String(length=64), nullable=False),
    sa.Column('chat_type', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('language_code', sa.String(length=32), nullable=True),
    sa.Column('alerts_enabled', sa.Boolean(), nullable=False),
    sa.Column('assistant_enabled', sa.Boolean(), nullable=False),
    sa.Column('is_blocked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_inbound_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_outbound_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telegram_chats_telegram_chat_id'), 'telegram_chats', ['telegram_chat_id'], unique=True)
    op.create_table('telegram_state',
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('admin_api_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['admin_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_api_tokens_token_hash'), 'admin_api_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_admin_api_tokens_user_id'), 'admin_api_tokens', ['user_id'], unique=False)
    op.create_table('admin_audit_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=120), nullable=False),
    sa.Column('resource_type', sa.String(length=80), nullable=False),
    sa.Column('resource_id', sa.String(length=120), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('event_metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['admin_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_audit_events_user_id'), 'admin_audit_events', ['user_id'], unique=False)
    op.create_table('analysis_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filing_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('language', sa.String(length=16), nullable=False),
    sa.Column('impact_label', sa.String(length=16), nullable=False),
    sa.Column('summary_text', sa.Text(), nullable=False),
    sa.Column('key_takeaways', sa.JSON(), nullable=False),
    sa.Column('raw_payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['filing_id'], ['filings.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('filing_id')
    )
    op.create_table('evaluation_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('label_type', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('total_examples', sa.Integer(), nullable=False),
    sa.Column('completed_examples', sa.Integer(), nullable=False),
    sa.Column('impact_accuracy', sa.Float(), nullable=True),
    sa.Column('summary_similarity_mean', sa.Float(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('run_metadata', sa.JSON(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['admin_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('filing_chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filing_id', sa.Integer(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('purpose', sa.String(length=32), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('char_count', sa.Integer(), nullable=False),
    sa.Column('token_estimate', sa.Integer(), nullable=False),
    sa.Column('chunk_metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['filing_id'], ['filings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_filing_chunks_filing_id'), 'filing_chunks', ['filing_id'], unique=False)
    op.create_table('telegram_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('telegram_update_id', sa.String(length=64), nullable=True),
    sa.Column('telegram_message_id', sa.String(length=64), nullable=True),
    sa.Column('direction', sa.String(length=16), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('command_name', sa.String(length=64), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=True),
    sa.Column('model', sa.String(length=128), nullable=True),
    sa.Column('message_metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['telegram_chats.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_update_id')
    )
    op.create_index(op.f('ix_telegram_messages_chat_id'), 'telegram_messages', ['chat_id'], unique=False)
    op.create_table('filing_chunk_embeddings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chunk_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('dimensions', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('vector', sa.JSON(), nullable=True),
    sa.Column('raw_payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['filing_chunks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chunk_id', 'provider', 'model', name='uq_chunk_embedding_provider_model')
    )
    op.create_index(op.f('ix_filing_chunk_embeddings_chunk_id'), 'filing_chunk_embeddings', ['chunk_id'], unique=False)
    op.create_table('label_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filing_id', sa.Integer(), nullable=True),
    sa.Column('analysis_result_id', sa.Integer(), nullable=True),
    sa.Column('chunk_id', sa.Integer(), nullable=True),
    sa.Column('task_type', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('task_metadata', sa.JSON(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('assigned_to_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['analysis_result_id'], ['analysis_results.id'], ),
    sa.ForeignKeyConstraint(['assigned_to_user_id'], ['admin_users.id'], ),
    sa.ForeignKeyConstraint(['chunk_id'], ['filing_chunks.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['admin_users.id'], ),
    sa.ForeignKeyConstraint(['filing_id'], ['filings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_label_tasks_analysis_result_id'), 'label_tasks', ['analysis_result_id'], unique=False)
    op.create_index(op.f('ix_label_tasks_chunk_id'), 'label_tasks', ['chunk_id'], unique=False)
    op.create_index(op.f('ix_label_tasks_filing_id'), 'label_tasks', ['filing_id'], unique=False)
    op.create_table('label_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('filing_id', sa.Integer(), nullable=True),
    sa.Column('analysis_result_id', sa.Integer(), nullable=True),
    sa.Column('chunk_id', sa.Integer(), nullable=True),
    sa.Column('labeler_user_id', sa.Integer(), nullable=True),
    sa.Column('label_type', sa.String(length=64), nullable=False),
    sa.Column('impact_label', sa.String(length=16), nullable=True),
    sa.Column('relevance_label', sa.String(length=32), nullable=True),
    sa.Column('summary_text', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('label_payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['analysis_result_id'], ['analysis_results.id'], ),
    sa.ForeignKeyConstraint(['chunk_id'], ['filing_chunks.id'], ),
    sa.ForeignKeyConstraint(['filing_id'], ['filings.id'], ),
    sa.ForeignKeyConstraint(['labeler_user_id'], ['admin_users.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['label_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_label_records_analysis_result_id'), 'label_records', ['analysis_result_id'], unique=False)
    op.create_index(op.f('ix_label_records_chunk_id'), 'label_records', ['chunk_id'], unique=False)
    op.create_index(op.f('ix_label_records_filing_id'), 'label_records', ['filing_id'], unique=False)
    op.create_index(op.f('ix_label_records_labeler_user_id'), 'label_records', ['labeler_user_id'], unique=False)
    op.create_index(op.f('ix_label_records_task_id'), 'label_records', ['task_id'], unique=False)
    op.create_table('evaluation_examples',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evaluation_run_id', sa.Integer(), nullable=False),
    sa.Column('filing_id', sa.Integer(), nullable=False),
    sa.Column('label_record_id', sa.Integer(), nullable=False),
    sa.Column('predicted_impact', sa.String(length=16), nullable=True),
    sa.Column('predicted_summary', sa.Text(), nullable=True),
    sa.Column('predicted_takeaways', sa.JSON(), nullable=False),
    sa.Column('impact_match', sa.Boolean(), nullable=True),
    sa.Column('summary_similarity', sa.Float(), nullable=True),
    sa.Column('raw_payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['evaluation_run_id'], ['evaluation_runs.id'], ),
    sa.ForeignKeyConstraint(['filing_id'], ['filings.id'], ),
    sa.ForeignKeyConstraint(['label_record_id'], ['label_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evaluation_examples_evaluation_run_id'), 'evaluation_examples', ['evaluation_run_id'], unique=False)
    op.create_index(op.f('ix_evaluation_examples_filing_id'), 'evaluation_examples', ['filing_id'], unique=False)
    op.create_index(op.f('ix_evaluation_examples_label_record_id'), 'evaluation_examples', ['label_record_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_evaluation_examples_label_record_id'), table_name='evaluation_examples')
    op.drop_index(op.f('ix_evaluation_examples_filing_id'), table_name='evaluation_examples')
    op.drop_index(op.f('ix_evaluation_examples_evaluation_run_id'), table_name='evaluation_examples')
    op.drop_table('evaluation_examples')
    op.drop_index(op.f('ix_label_records_task_id'), table_name='label_records')
    op.drop_index(op.f('ix_label_records_labeler_user_id'), table_name='label_records')
    op.drop_index(op.f('ix_label_records_filing_id'), table_name='label_records')
    op.drop_index(op.f('ix_label_records_chunk_id'), table_name='label_records')
    op.drop_index(op.f('ix_label_records_analysis_result_id'), table_name='label_records')
    op.drop_table('label_records')
    op.drop_index(op.f('ix_label_tasks_filing_id'), table_name='label_tasks')
    op.drop_index(op.f('ix_label_tasks_chunk_id'), table_name='label_tasks')
    op.drop_index(op.f('ix_label_tasks_analysis_result_id'), table_name='label_tasks')
    op.drop_table('label_tasks')
    op.drop_index(op.f('ix_filing_chunk_embeddings_chunk_id'), table_name='filing_chunk_embeddings')
    op.drop_table('filing_chunk_embeddings')
    op.drop_index(op.f('ix_telegram_messages_chat_id'), table_name='telegram_messages')
    op.drop_table('telegram_messages')
    op.drop_index(op.f('ix_filing_chunks_filing_id'), table_name='filing_chunks')
    op.drop_table('filing_chunks')
    op.drop_table('evaluation_runs')
    op.drop_table('analysis_results')
    op.drop_index(op.f('ix_admin_audit_events_user_id'), table_name='admin_audit_events')
    op.drop_table('admin_audit_events')
    op.drop_index(op.f('ix_admin_api_tokens_user_id'), table_name='admin_api_tokens')
    op.drop_index(op.f('ix_admin_api_tokens_token_hash'), table_name='admin_api_tokens')
    op.drop_table('admin_api_tokens')
    op.drop_table('telegram_state')
    op.drop_index(op.f('ix_telegram_chats_telegram_chat_id'), table_name='telegram_chats')
    op.drop_table('telegram_chats')
    op.drop_index(op.f('ix_price_snapshots_ticker'), table_name='price_snapshots')
    op.drop_index(op.f('ix_price_snapshots_fetched_at'), table_name='price_snapshots')
    op.drop_table('price_snapshots')
    op.drop_table('price_ingestion_runs')
    op.drop_index(op.f('ix_llm_usage_snapshots_synced_at'), table_name='llm_usage_snapshots')
    op.drop_index(op.f('ix_llm_usage_snapshots_provider'), table_name='llm_usage_snapshots')
    op.drop_index(op.f('ix_llm_usage_snapshots_period_key'), table_name='llm_usage_snapshots')
    op.drop_table('llm_usage_snapshots')
    op.drop_index(op.f('ix_llm_usage_events_provider'), table_name='llm_usage_events')
    op.drop_index(op.f('ix_llm_usage_events_created_at'), table_name='llm_usage_events')
    op.drop_table('llm_usage_events')
    op.drop_index(op.f('ix_llm_usage_alert_events_provider'), table_name='llm_usage_alert_events')
    op.drop_index(op.f('ix_llm_usage_alert_events_period_key'), table_name='llm_usage_alert_events')
    op.drop_table('llm_usage_alert_events')
    op.drop_table('ingestion_runs')
    op.drop_index(op.f('ix_filings_tier'), table_name='filings')
    op.drop_index(op.f('ix_filings_ticker'), table_name='filings')
    op.drop_index(op.f('ix_filings_published_at'), table_name='filings')
    op.drop_index(op.f('ix_filings_form_type'), table_name='filings')
    op.drop_index(op.f('ix_filings_entry_link'), table_name='filings')
    op.drop_index(op.f('ix_filings_accession_number'), table_name='filings')
    op.drop_table('filings')
    op.drop_table('app_config_entries')
    op.drop_index(op.f('ix_admin_users_username'), table_name='admin_users')
    op.drop_table('admin_users')
    # ### end Alembic commands ###
