WATCHLIST = [
    "DNN",
    "SMR",
    "UUUU",
    "UAMY",
    "USAR",
    "AMPX",
    "LCID",
    "RKLB",
    "QBTS",
    "NVDA",
    "AMD",
    "INTC",
    "ARM",
    "AVGO",
    "MRVL",
    "NVTS",
    "SMCI",
    "ASML",
    "MU",
    "TSM",
    "ON",
    "AMAT",
    "NOK",
    "SNDK",
    "MSFT",
    "GOOGL",
    "IBM",
    "ORCL",
    "AAPL",
    "VRT",
    "CLS",
    "TMUS",
    "PLTR",
    "FCX",
    "AG",
    "SLB",
    "CRML",
    "MTRN",
    "VOO",
    "SPY",
    "QQQ",
    "EQT",
    "ONDS",
]


TICKER_NAMES = {
    "AAPL": "Apple",
    "NVDA": "NVIDIA",
    "MSFT": "Microsoft",
    "GOOGL": "Alphabet",
    "AMD": "Advanced Micro Devices",
    "INTC": "Intel",
    "TSLA": "Tesla",
    "AVGO": "Broadcom",
    "ARM": "ARM Holdings",
    "ASML": "ASML",
    "MU": "Micron Technology",
    "TSM": "Taiwan Semiconductor",
    "AMAT": "Applied Materials",
    "MRVL": "Marvell Technology",
    "SMCI": "Super Micro Computer",
    "NVTS": "Navitas Semiconductor",
    "SNDK": "SanDisk",
    "NOK": "Nokia",
    "ON": "ON Semiconductor",
    "IBM": "International Business Machines",
    "ORCL": "Oracle",
    "PLTR": "Palantir",
    "TMUS": "T-Mobile",
    "VRT": "Vertiv",
    "CLS": "Celestica",
    "LCID": "Lucid Group",
    "AMPX": "Amprius",
    "RKLB": "Rocket Lab",
    "QBTS": "D-Wave Quantum",
    "DNN": "Denison Mines",
    "SMR": "NuScale Power",
    "UUUU": "Energy Fuels",
    "UAMY": "United States Antimony",
    "USAR": "US Nuclear",
    "FCX": "Freeport-McMoRan",
    "AG": "First Majestic Silver",
    "SLB": "Schlumberger",
    "CRML": "Critical Metals",
    "MTRN": "Materion",
    "EQT": "EQT Corp",
    "ONDS": "Ondas Holdings",
    "VOO": "Vanguard 500",
    "SPY": "SPDR S&P 500",
    "QQQ": "Invesco QQQ",
}


SEC_ITEM_NOTES_YUE = {
    "1.01": "簽大單 / 併購 / 融資",
    "1.02": "取消合約 / 大單告吹",
    "1.03": "破產 / 被接管",
    "1.04": "更換核數師",
    "2.01": "完成收購 / 賣盤",
    "2.02": "公布業績 / 更新指引",
    "3.01": "收到退市警告",
    "3.02": "配股 / 發債，可能攤薄",
    "4.02": "歷史財報存在問題，需要重列",
    "5.01": "控制權變更",
    "5.02": "CEO 或高層變動",
    "5.07": "股東大會投票結果",
    "7.01": "投資者簡報 / 對外通訊",
    "8.01": "其他重大事件",
    "9.01": "附件 / 新聞稿",
}

